### ISSUE TITLE
returnUrl issue

### ISSUE THREAD

**Issue by tudorached** [SantiagoInteractive/mobilpay-card-gateway-for-woocommerce#3]
Hi,

The returnUrl sent by _$this->get_return_url($order)_ is not beeing recognised by mobilpay.

```php
$objPmReqCard->returnUrl  = $this->get_return_url($order);
```
**should be replaced with:**
```php
$objPmReqCard->returnUrl  = str_replace( '&', '&amp;',  $this->get_return_url($order) );
```

**Comment by SantiagoInteractive** [comment]
Hi,

Also working without doing this. Just tested right now with and without your fix and works just fine in both cases. What was the error you were receiving before doing this change? Can you please provide more information?

Thanks!

**Comment by tudorached** [comment]
More information:
Mobilpay degresses to the return url settings found in the user account, on mobilpay's website. I have tested the plugin on two different websites hosted on different servers. Making that change solves the problem.

Might be caused because of php's mbstring extension, which I've activated recently because Woocommerce emails were not rendered correctly. 

I will test without mbstring and come back with the results.

**Comment by SantiagoInteractive** [comment]
Tested with mbstring extension on. Works both ways.

**Comment by SantiagoInteractive** [comment]
What's your return url structure? Check under: mobilpay panel > order details > api tab.
It should be like: website-url/checkout/order-received/numeric-order-id?key=wc_order_some-string

If not, try saving again your permalink structure under wp-admin panel > settings > permalinks.

**Comment by tudorached** [comment]
Until I did the change the return node was empty
```xml
<return/>
```

**Comment by SantiagoInteractive** [comment]
I understand. I will commit your change.
Thank you for sharing!

**Comment by tudorached** [comment]
Thanks for creating the plugin!

**Comment by SantiagoInteractive** [comment]
You're welcome! 👍

**Comment by SantiagoInteractive** [comment]
https://github.com/SantiagoInteractive/mobilpay-card-gateway-for-woocommerce/commit/04dbcf2e99e1f02079ac5283544935976a9326a0#diff-04fa96050c19d66b0302739443f68a47R274
